apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-contenedor
        image: lauragg17/cra  # Reemplaza con tu imagen de Docker
        ports:
        - containerPort: 5173  # Puerto en el que la aplicación escucha
