apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
spec:
  type: NodePort  # Exponemos el servicio usando NodePort
  ports:
  - port: 80          # Puerto en el que el servicio escucha
    targetPort: 5173  # Puerto en el contenedor donde la app está escuchando
  selector:
    app: mi-aplicacion
